apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.configMapName }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    {{- toYaml .Values.prometheus.config | nindent 4 }}