apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager.fullname" . }}-auth
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
type: Opaque
data:
  # Token pour l'API AlertManager
  api-token: {{ randAlphaNum 32 | b64enc }}
  # Webhook secret pour les intégrations
  webhook-secret: {{ randAlphaNum 64 | b64enc }}